// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft_consensus.proto

// Protobuf Java Version: 3.25.3
package com.foodtraceability.agent.consensus.grpc;

public interface BlockNotificationProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BlockNotificationProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string block_hash = 1;</code>
   * @return The blockHash.
   */
  java.lang.String getBlockHash();
  /**
   * <code>string block_hash = 1;</code>
   * @return The bytes for blockHash.
   */
  com.google.protobuf.ByteString
      getBlockHashBytes();

  /**
   * <code>string food_id = 2;</code>
   * @return The foodId.
   */
  java.lang.String getFoodId();
  /**
   * <code>string food_id = 2;</code>
   * @return The bytes for foodId.
   */
  com.google.protobuf.ByteString
      getFoodIdBytes();

  /**
   * <code>string chain_type = 3;</code>
   * @return The chainType.
   */
  java.lang.String getChainType();
  /**
   * <code>string chain_type = 3;</code>
   * @return The bytes for chainType.
   */
  com.google.protobuf.ByteString
      getChainTypeBytes();

  /**
   * <code>int64 block_header_id = 4;</code>
   * @return The blockHeaderId.
   */
  long getBlockHeaderId();
}
