// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft_consensus.proto

// Protobuf Java Version: 3.25.3
package com.foodtraceability.agent.consensus.grpc;

/**
 * Protobuf type {@code BlockNotificationProto}
 */
public final class BlockNotificationProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BlockNotificationProto)
    BlockNotificationProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BlockNotificationProto.newBuilder() to construct.
  private BlockNotificationProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BlockNotificationProto() {
    blockHash_ = "";
    foodId_ = "";
    chainType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BlockNotificationProto();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.foodtraceability.agent.consensus.grpc.PbftConsensus.internal_static_BlockNotificationProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.foodtraceability.agent.consensus.grpc.PbftConsensus.internal_static_BlockNotificationProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.foodtraceability.agent.consensus.grpc.BlockNotificationProto.class, com.foodtraceability.agent.consensus.grpc.BlockNotificationProto.Builder.class);
  }

  public static final int BLOCK_HASH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object blockHash_ = "";
  /**
   * <code>string block_hash = 1;</code>
   * @return The blockHash.
   */
  @java.lang.Override
  public java.lang.String getBlockHash() {
    java.lang.Object ref = blockHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      blockHash_ = s;
      return s;
    }
  }
  /**
   * <code>string block_hash = 1;</code>
   * @return The bytes for blockHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBlockHashBytes() {
    java.lang.Object ref = blockHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      blockHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FOOD_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object foodId_ = "";
  /**
   * <code>string food_id = 2;</code>
   * @return The foodId.
   */
  @java.lang.Override
  public java.lang.String getFoodId() {
    java.lang.Object ref = foodId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      foodId_ = s;
      return s;
    }
  }
  /**
   * <code>string food_id = 2;</code>
   * @return The bytes for foodId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFoodIdBytes() {
    java.lang.Object ref = foodId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      foodId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHAIN_TYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object chainType_ = "";
  /**
   * <code>string chain_type = 3;</code>
   * @return The chainType.
   */
  @java.lang.Override
  public java.lang.String getChainType() {
    java.lang.Object ref = chainType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chainType_ = s;
      return s;
    }
  }
  /**
   * <code>string chain_type = 3;</code>
   * @return The bytes for chainType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChainTypeBytes() {
    java.lang.Object ref = chainType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chainType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BLOCK_HEADER_ID_FIELD_NUMBER = 4;
  private long blockHeaderId_ = 0L;
  /**
   * <code>int64 block_header_id = 4;</code>
   * @return The blockHeaderId.
   */
  @java.lang.Override
  public long getBlockHeaderId() {
    return blockHeaderId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockHash_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, blockHash_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(foodId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, foodId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chainType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, chainType_);
    }
    if (blockHeaderId_ != 0L) {
      output.writeInt64(4, blockHeaderId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockHash_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, blockHash_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(foodId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, foodId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chainType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, chainType_);
    }
    if (blockHeaderId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, blockHeaderId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.foodtraceability.agent.consensus.grpc.BlockNotificationProto)) {
      return super.equals(obj);
    }
    com.foodtraceability.agent.consensus.grpc.BlockNotificationProto other = (com.foodtraceability.agent.consensus.grpc.BlockNotificationProto) obj;

    if (!getBlockHash()
        .equals(other.getBlockHash())) return false;
    if (!getFoodId()
        .equals(other.getFoodId())) return false;
    if (!getChainType()
        .equals(other.getChainType())) return false;
    if (getBlockHeaderId()
        != other.getBlockHeaderId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BLOCK_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getBlockHash().hashCode();
    hash = (37 * hash) + FOOD_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFoodId().hashCode();
    hash = (37 * hash) + CHAIN_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getChainType().hashCode();
    hash = (37 * hash) + BLOCK_HEADER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlockHeaderId());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.foodtraceability.agent.consensus.grpc.BlockNotificationProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.foodtraceability.agent.consensus.grpc.BlockNotificationProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.foodtraceability.agent.consensus.grpc.BlockNotificationProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.foodtraceability.agent.consensus.grpc.BlockNotificationProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.foodtraceability.agent.consensus.grpc.BlockNotificationProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.foodtraceability.agent.consensus.grpc.BlockNotificationProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.foodtraceability.agent.consensus.grpc.BlockNotificationProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.foodtraceability.agent.consensus.grpc.BlockNotificationProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.foodtraceability.agent.consensus.grpc.BlockNotificationProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.foodtraceability.agent.consensus.grpc.BlockNotificationProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.foodtraceability.agent.consensus.grpc.BlockNotificationProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.foodtraceability.agent.consensus.grpc.BlockNotificationProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.foodtraceability.agent.consensus.grpc.BlockNotificationProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BlockNotificationProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BlockNotificationProto)
      com.foodtraceability.agent.consensus.grpc.BlockNotificationProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.foodtraceability.agent.consensus.grpc.PbftConsensus.internal_static_BlockNotificationProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.foodtraceability.agent.consensus.grpc.PbftConsensus.internal_static_BlockNotificationProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.foodtraceability.agent.consensus.grpc.BlockNotificationProto.class, com.foodtraceability.agent.consensus.grpc.BlockNotificationProto.Builder.class);
    }

    // Construct using com.foodtraceability.agent.consensus.grpc.BlockNotificationProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      blockHash_ = "";
      foodId_ = "";
      chainType_ = "";
      blockHeaderId_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.foodtraceability.agent.consensus.grpc.PbftConsensus.internal_static_BlockNotificationProto_descriptor;
    }

    @java.lang.Override
    public com.foodtraceability.agent.consensus.grpc.BlockNotificationProto getDefaultInstanceForType() {
      return com.foodtraceability.agent.consensus.grpc.BlockNotificationProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.foodtraceability.agent.consensus.grpc.BlockNotificationProto build() {
      com.foodtraceability.agent.consensus.grpc.BlockNotificationProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.foodtraceability.agent.consensus.grpc.BlockNotificationProto buildPartial() {
      com.foodtraceability.agent.consensus.grpc.BlockNotificationProto result = new com.foodtraceability.agent.consensus.grpc.BlockNotificationProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.foodtraceability.agent.consensus.grpc.BlockNotificationProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.blockHash_ = blockHash_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.foodId_ = foodId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.chainType_ = chainType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.blockHeaderId_ = blockHeaderId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.foodtraceability.agent.consensus.grpc.BlockNotificationProto) {
        return mergeFrom((com.foodtraceability.agent.consensus.grpc.BlockNotificationProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.foodtraceability.agent.consensus.grpc.BlockNotificationProto other) {
      if (other == com.foodtraceability.agent.consensus.grpc.BlockNotificationProto.getDefaultInstance()) return this;
      if (!other.getBlockHash().isEmpty()) {
        blockHash_ = other.blockHash_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getFoodId().isEmpty()) {
        foodId_ = other.foodId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getChainType().isEmpty()) {
        chainType_ = other.chainType_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getBlockHeaderId() != 0L) {
        setBlockHeaderId(other.getBlockHeaderId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              blockHash_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              foodId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              chainType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              blockHeaderId_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object blockHash_ = "";
    /**
     * <code>string block_hash = 1;</code>
     * @return The blockHash.
     */
    public java.lang.String getBlockHash() {
      java.lang.Object ref = blockHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        blockHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string block_hash = 1;</code>
     * @return The bytes for blockHash.
     */
    public com.google.protobuf.ByteString
        getBlockHashBytes() {
      java.lang.Object ref = blockHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blockHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string block_hash = 1;</code>
     * @param value The blockHash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockHash(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      blockHash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string block_hash = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockHash() {
      blockHash_ = getDefaultInstance().getBlockHash();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string block_hash = 1;</code>
     * @param value The bytes for blockHash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      blockHash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object foodId_ = "";
    /**
     * <code>string food_id = 2;</code>
     * @return The foodId.
     */
    public java.lang.String getFoodId() {
      java.lang.Object ref = foodId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        foodId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string food_id = 2;</code>
     * @return The bytes for foodId.
     */
    public com.google.protobuf.ByteString
        getFoodIdBytes() {
      java.lang.Object ref = foodId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        foodId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string food_id = 2;</code>
     * @param value The foodId to set.
     * @return This builder for chaining.
     */
    public Builder setFoodId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      foodId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string food_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFoodId() {
      foodId_ = getDefaultInstance().getFoodId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string food_id = 2;</code>
     * @param value The bytes for foodId to set.
     * @return This builder for chaining.
     */
    public Builder setFoodIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      foodId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object chainType_ = "";
    /**
     * <code>string chain_type = 3;</code>
     * @return The chainType.
     */
    public java.lang.String getChainType() {
      java.lang.Object ref = chainType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chainType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string chain_type = 3;</code>
     * @return The bytes for chainType.
     */
    public com.google.protobuf.ByteString
        getChainTypeBytes() {
      java.lang.Object ref = chainType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chainType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string chain_type = 3;</code>
     * @param value The chainType to set.
     * @return This builder for chaining.
     */
    public Builder setChainType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      chainType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string chain_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearChainType() {
      chainType_ = getDefaultInstance().getChainType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string chain_type = 3;</code>
     * @param value The bytes for chainType to set.
     * @return This builder for chaining.
     */
    public Builder setChainTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      chainType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long blockHeaderId_ ;
    /**
     * <code>int64 block_header_id = 4;</code>
     * @return The blockHeaderId.
     */
    @java.lang.Override
    public long getBlockHeaderId() {
      return blockHeaderId_;
    }
    /**
     * <code>int64 block_header_id = 4;</code>
     * @param value The blockHeaderId to set.
     * @return This builder for chaining.
     */
    public Builder setBlockHeaderId(long value) {

      blockHeaderId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 block_header_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockHeaderId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      blockHeaderId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BlockNotificationProto)
  }

  // @@protoc_insertion_point(class_scope:BlockNotificationProto)
  private static final com.foodtraceability.agent.consensus.grpc.BlockNotificationProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.foodtraceability.agent.consensus.grpc.BlockNotificationProto();
  }

  public static com.foodtraceability.agent.consensus.grpc.BlockNotificationProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlockNotificationProto>
      PARSER = new com.google.protobuf.AbstractParser<BlockNotificationProto>() {
    @java.lang.Override
    public BlockNotificationProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BlockNotificationProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlockNotificationProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.foodtraceability.agent.consensus.grpc.BlockNotificationProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

