// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft_consensus.proto

// Protobuf Java Version: 3.25.3
package com.foodtraceability.agent.consensus.grpc;

public interface ConsensusRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConsensusRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string context = 1;</code>
   * @return The context.
   */
  java.lang.String getContext();
  /**
   * <code>string context = 1;</code>
   * @return The bytes for context.
   */
  com.google.protobuf.ByteString
      getContextBytes();

  /**
   * <code>string digest = 2;</code>
   * @return The digest.
   */
  java.lang.String getDigest();
  /**
   * <code>string digest = 2;</code>
   * @return The bytes for digest.
   */
  com.google.protobuf.ByteString
      getDigestBytes();
}
