// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft_consensus.proto

// Protobuf Java Version: 3.25.3
package com.foodtraceability.agent.consensus.grpc;

public interface EndorsementResponseProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EndorsementResponseProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string agent_id = 1;</code>
   * @return The agentId.
   */
  java.lang.String getAgentId();
  /**
   * <code>string agent_id = 1;</code>
   * @return The bytes for agentId.
   */
  com.google.protobuf.ByteString
      getAgentIdBytes();

  /**
   * <code>bool approved = 2;</code>
   * @return The approved.
   */
  boolean getApproved();

  /**
   * <code>string signature = 3;</code>
   * @return The signature.
   */
  java.lang.String getSignature();
  /**
   * <code>string signature = 3;</code>
   * @return The bytes for signature.
   */
  com.google.protobuf.ByteString
      getSignatureBytes();

  /**
   * <code>string reason = 4;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 4;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
