// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft_consensus.proto

// Protobuf Java Version: 3.25.3
package com.foodtraceability.agent.consensus.grpc;

public interface EndorsementRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EndorsementRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string context = 1;</code>
   * @return The context.
   */
  java.lang.String getContext();
  /**
   * <code>string context = 1;</code>
   * @return The bytes for context.
   */
  com.google.protobuf.ByteString
      getContextBytes();

  /**
   * <code>string digest = 2;</code>
   * @return The digest.
   */
  java.lang.String getDigest();
  /**
   * <code>string digest = 2;</code>
   * @return The bytes for digest.
   */
  com.google.protobuf.ByteString
      getDigestBytes();

  /**
   * <code>string requesting_agent = 3;</code>
   * @return The requestingAgent.
   */
  java.lang.String getRequestingAgent();
  /**
   * <code>string requesting_agent = 3;</code>
   * @return The bytes for requestingAgent.
   */
  com.google.protobuf.ByteString
      getRequestingAgentBytes();
}
