// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft_consensus.proto

// Protobuf Java Version: 3.25.3
package com.foodtraceability.agent.consensus.grpc;

public final class PbftConsensus {
  private PbftConsensus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PbftMessageProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PbftMessageProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EndorsementRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EndorsementRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EndorsementResponseProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EndorsementResponseProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConsensusRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConsensusRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConsensusResponseProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConsensusResponseProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BlockNotificationProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BlockNotificationProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AckResponseProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AckResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024pbft_consensus.proto\"\220\001\n\020PbftMessagePr" +
      "oto\022\014\n\004type\030\001 \001(\t\022\014\n\004view\030\002 \001(\t\022\027\n\017seque" +
      "nce_number\030\003 \001(\003\022\016\n\006digest\030\004 \001(\t\022\021\n\tsend" +
      "er_id\030\005 \001(\t\022\021\n\tsignature\030\006 \001(\t\022\021\n\ttimest" +
      "amp\030\007 \001(\003\"T\n\027EndorsementRequestProto\022\017\n\007" +
      "context\030\001 \001(\t\022\016\n\006digest\030\002 \001(\t\022\030\n\020request" +
      "ing_agent\030\003 \001(\t\"a\n\030EndorsementResponsePr" +
      "oto\022\020\n\010agent_id\030\001 \001(\t\022\020\n\010approved\030\002 \001(\010\022" +
      "\021\n\tsignature\030\003 \001(\t\022\016\n\006reason\030\004 \001(\t\"8\n\025Co" +
      "nsensusRequestProto\022\017\n\007context\030\001 \001(\t\022\016\n\006" +
      "digest\030\002 \001(\t\"S\n\026ConsensusResponseProto\022\017" +
      "\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\022\027\n\017sequ" +
      "ence_number\030\003 \001(\003\"j\n\026BlockNotificationPr" +
      "oto\022\022\n\nblock_hash\030\001 \001(\t\022\017\n\007food_id\030\002 \001(\t" +
      "\022\022\n\nchain_type\030\003 \001(\t\022\027\n\017block_header_id\030" +
      "\004 \001(\003\"4\n\020AckResponseProto\022\017\n\007success\030\001 \001" +
      "(\010\022\017\n\007message\030\002 \001(\t2\364\002\n\020ConsensusService" +
      "\022D\n\021InitiateConsensus\022\026.ConsensusRequest" +
      "Proto\032\027.ConsensusResponseProto\022>\n\007Endors" +
      "e\022\030.EndorsementRequestProto\032\031.Endorsemen" +
      "tResponseProto\0226\n\016SendPrePrepare\022\021.PbftM" +
      "essageProto\032\021.AckResponseProto\0223\n\013SendPr" +
      "epare\022\021.PbftMessageProto\032\021.AckResponsePr" +
      "oto\0222\n\nSendCommit\022\021.PbftMessageProto\032\021.A" +
      "ckResponseProto\0229\n\013NotifyBlock\022\027.BlockNo" +
      "tificationProto\032\021.AckResponseProtoB-\n)co" +
      "m.foodtraceability.agent.consensus.grpcP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PbftMessageProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PbftMessageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PbftMessageProto_descriptor,
        new java.lang.String[] { "Type", "View", "SequenceNumber", "Digest", "SenderId", "Signature", "Timestamp", });
    internal_static_EndorsementRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EndorsementRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EndorsementRequestProto_descriptor,
        new java.lang.String[] { "Context", "Digest", "RequestingAgent", });
    internal_static_EndorsementResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EndorsementResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EndorsementResponseProto_descriptor,
        new java.lang.String[] { "AgentId", "Approved", "Signature", "Reason", });
    internal_static_ConsensusRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ConsensusRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConsensusRequestProto_descriptor,
        new java.lang.String[] { "Context", "Digest", });
    internal_static_ConsensusResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ConsensusResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConsensusResponseProto_descriptor,
        new java.lang.String[] { "Success", "Message", "SequenceNumber", });
    internal_static_BlockNotificationProto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_BlockNotificationProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BlockNotificationProto_descriptor,
        new java.lang.String[] { "BlockHash", "FoodId", "ChainType", "BlockHeaderId", });
    internal_static_AckResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_AckResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AckResponseProto_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
