// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft_consensus.proto

// Protobuf Java Version: 3.25.3
package com.foodtraceability.agent.consensus.grpc;

public interface PbftMessageProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PbftMessageProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string view = 2;</code>
   * @return The view.
   */
  java.lang.String getView();
  /**
   * <code>string view = 2;</code>
   * @return The bytes for view.
   */
  com.google.protobuf.ByteString
      getViewBytes();

  /**
   * <code>int64 sequence_number = 3;</code>
   * @return The sequenceNumber.
   */
  long getSequenceNumber();

  /**
   * <code>string digest = 4;</code>
   * @return The digest.
   */
  java.lang.String getDigest();
  /**
   * <code>string digest = 4;</code>
   * @return The bytes for digest.
   */
  com.google.protobuf.ByteString
      getDigestBytes();

  /**
   * <code>string sender_id = 5;</code>
   * @return The senderId.
   */
  java.lang.String getSenderId();
  /**
   * <code>string sender_id = 5;</code>
   * @return The bytes for senderId.
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string signature = 6;</code>
   * @return The signature.
   */
  java.lang.String getSignature();
  /**
   * <code>string signature = 6;</code>
   * @return The bytes for signature.
   */
  com.google.protobuf.ByteString
      getSignatureBytes();

  /**
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
