export const AGENT_TYPES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  PRODUCTION: 'PRODUCTION',
  CIRCULATION: 'CIRCULATION',
  SALES: 'SALES'
}

const MENU_PERMISSIONS = {
  dashboard: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.PRODUCTION, AGENT_TYPES.CIRCULATION, AGENT_TYPES.SALES],
  products: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.PRODUCTION, AGENT_TYPES.CIRCULATION, AGENT_TYPES.SALES],
  materials: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.PRODUCTION],
  batches: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.PRODUCTION],
  storages: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.CIRCULATION],
  transports: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.CIRCULATION, AGENT_TYPES.SALES],
  inspections: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.PRODUCTION],
  complaints: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.SALES],
  blockchain: [AGENT_TYPES.SUPER_ADMIN],
  agents: [AGENT_TYPES.SUPER_ADMIN],
  companies: [AGENT_TYPES.SUPER_ADMIN],
  admins: [AGENT_TYPES.SUPER_ADMIN]
}

const WRITE_PERMISSIONS = {
  products: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.PRODUCTION],
  materials: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.PRODUCTION],
  batches: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.PRODUCTION],
  storages: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.CIRCULATION],
  transports: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.CIRCULATION, AGENT_TYPES.SALES],
  inspections: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.PRODUCTION],
  complaints: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.SALES],
  materialPurchases: [AGENT_TYPES.SUPER_ADMIN, AGENT_TYPES.PRODUCTION]
}

export function canAccessMenu(menuKey, agentType) {
  const allowed = MENU_PERMISSIONS[menuKey]
  return allowed ? allowed.includes(agentType) : false
}

export function canWrite(moduleKey, agentType) {
  const allowed = WRITE_PERMISSIONS[moduleKey]
  return allowed ? allowed.includes(agentType) : false
}

export function requiresSuperAdmin(agentType) {
  return agentType === AGENT_TYPES.SUPER_ADMIN
}
